# These are supported funding model platforms.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom:
  - https://donate.stripe.com/eVq4gy97DanS9h60phfrW00
